AMPLATE = {}

AMPLATE.BlacklistedPlates = {
    'Desudo',
    'LynxMenu',
    'AKTeam',
    'Ancient',
    'BRUTAN',
    'Brutan#7799',
    'Cookie',
    'AlikhanMenu',
    'GEJ',
    'LYNX',
    'CK GANG',
    'Tiago',
    'Swag Menu',
    'HamHaxia',
    'eulencheats',
    'EulenMenu',
    'Falcon',
    'GEJ',
    'Shadow',
    'AlphaV',
    'Luminous',
    'Lux Menu',
    'MalossiMenu V3',
    'Malossi',
    'obl2',
    'S1MLLER',
    'iSeekFR',
    'Skaza',
    'TITOModz',
    'ZajacMenu',
    'Menuxdhf798230fsdf3df Menu',
}